### ISSUE TITLE
Last Day of Week Wraps to New Line in FireFox

### ISSUE THREAD

**Issue by gbroques** [Adphorus/react-date-range#102]
The last day of the week wraps to a new line in FireFox. I'm currently on version `51.0.1`.

Here's a screenshot of the behavior:

![Screenshot](https://s24.postimg.org/h20n2289h/Screenshot_from_2017_02_01_14_47_10.png)

This behavior is not seen in Chrome, and I haven't tried any other browsers.

Changing the width of the div with class `rdr-Calendar` from `280px` to `281px` seems to fix it.

It'd be nice to not have to write a custom CSS rule for FireFox though.

**Comment by burakcan** [comment]
This should be fixed on 0.9.3. can you check please?

**Comment by daniula** [comment]
Still broken. Same FF version 51.0.1.

**Comment by TheSharpieOne** [comment]
I just ran into this as well using 0.9.4 on firefox 56.0 (64-bit) on MacOS 10.12.6 (16G29)
I think the issue itself is with firefox and how px values are rounded, but it can be fixed in the library (or even in user-land by overriding the styles on `.rdr-WeekDay` (with `$width`)). the [$width](https://github.com/Adphorus/react-date-range/blob/master/src/styles.scss#L98) could be rouded down to strip the decimal.

**Comment by primavera133** [comment]
Firefox rounds the calculated with of the cells from 37.1429px  => 37.15px (weird math) which makes the cells too big.

![image](https://user-images.githubusercontent.com/311424/33670516-93d0f546-daa5-11e7-9a5d-2d7affd8c511.png)
 
I fixed it in my app in theme settings for padding as suggested in https://github.com/Adphorus/react-date-range/issues/45

**Comment by mkg0** [comment]
please upgrade the new version to solve it
