### ISSUE TITLE
Highlighting while selecting a date range

### ISSUE THREAD

**Issue by MrSauceman** [Adphorus/react-date-range#134]
In the range calendar, it would be nice if when after selecting the start date, hovering over the end date (before choosing one) would highlight the dates within the range, perhaps in a lighter color than the final selected color.  This really helps visualize the range you are choosing and actually tells the user that they are selecting a range, which isn't immediately clear currently.

**Comment by daybreaker** [comment]
I was previously using another range selector that did this, and I think it's not that great in terms of UX.

It makes it confusing that you're able to click the "Next Month" button, because the illusion of being in the middle of an active selection makes a user hesitant to click anywhere other than the desired end point.

**Comment by MrSauceman** [comment]
Yes, optional prop is what I was thinking.  I would love to see this.

**Comment by mkg0** [comment]
included in the new version
