### ISSUE TITLE
Can't seem to use to select last 48h, last 72h, etc.

### ISSUE THREAD

**Issue by carlesandres** [Adphorus/react-date-range#37]
I know it probably makes little sense since a date picker is for picking, ahem, dates and not date-times. However, I'm already using `react-date-range` and I've been asked to provide some predefined links that (instead of just selecting "Today" or "Yesterday"), allow for easy selection of "Last 24h", "Last 48h" and the like.

As far as I could see, the use of `startOf('day')` across the codebase prevents such time spans from being selected with the component as it currently stands. 

Have you got any ideas as to how I could add that functionality without tampering with the widget?

Would you consider adding the ability to select non-start-of-the-day timestamps with a flag (something like an `allowNonFullDays` prop) if I decided to implement it?

**Comment by burakcan** [comment]
Hi @carlesandres 
Unfortunately current code doesn't support selecting time spans due to extensive usage of `startOf('day')` which you mentioned. But; you can convert them to their respective equivalents as days like 48h = last two days etc. for now.
I have future plans to add time selector functionality -which will eventually get you what you want- to the library but it requires a major rewrite and i'm not sure about it's timing since i'm a bit busy these days.

**Comment by carlesandres** [comment]
Thanks for the fast response @burakcan ! 

Until those changes come, I'll probably hack the `parseInput` utility to accept a third param which allows me to skip `startOf('day')`
