### ISSUE TITLE
Add way to select previous years quickly

### ISSUE THREAD

**Issue by AndrewMarkley** [Adphorus/react-date-range#62]
I don't see anyway to quickly select a different year.

I know some date pickers are setup so that when you click the date above the calendar it shows the months. then if you click the top of the calendar again it shows the last 10 year, clicking it again then shows you the last ten decades. Here is an example: https://eonasdan.github.io/bootstrap-datetimepicker/

Except for that, this is a fantastic component!

**Comment by m1n0s** [comment]
+1 need this functionality.

Maybe it will be some free time and I implement it by myself.

**Comment by sators** [comment]
+1

**Comment by manix** [comment]
+1

**Comment by thenano** [comment]
+1
This component is amazing, good look and feel and very light. I needed something for date of birth date selection and the only reason I couldn't use this is because there's no way to go back years quickly!

**Comment by OriR** [comment]
👍 
@burakcan This functionality is very needed, is there any way we can make that happen?
I don't mind making a PR but I'd appreciate some guidance on where to start and how do you see this being implemented.

**Comment by burakcan** [comment]
Hi all. Thank you for your interest. Unfortunately, I left Adphorus 4 months ago to move to another country and I'm a bit busy because of that. Really sorry for that.

When i first built this library, I wasn't expecting this much interest (actually, it was my onboarding project at Adphorus) and I didn't know what features are required. I'm working on a new version of the library -by reusing the existing parts-. This time it will be more complete feature wise and have some tests. But this will take some time; my plan is to release it at the end of April.

@OriR if you need this feature immediately, and want to implement it; you should start from the `src/Calendar.js` file. I think calendar should have a "mode" state which switches between day/month/year modes. When you click on the title, it switches to one level higher level. For example: if the current active mode is "day", when you click it it should be switching to "month". And if you select a month, then it should switch back to day. I don't think the mode needs to be synced between calendars in a range.

**Comment by mkg0** [comment]
Included in the new version
